ktor:
    deployment:
        sslPort:    8081
        host:       localhost
        autoreload: false
    security:
        ssl:
            keyStore: security/tls/keystore.p12
            keyStoreType: PKCS12
            keyAlias: mykeystore
            keyStorePassword: $KEYSTORE_PRIVATEKEY_CERTIFICATE_PASSWORD
            privateKeyPassword: $KEYSTORE_PRIVATEKEY_CERTIFICATE_PASSWORD
            clientAuth: none
    application:
        modules:
            - com.example.ApplicationKt.module

jwt:
    algorithm: RS256
    privateKeyPath: security/auth/private.pem
    publicKeyPath: security/auth/public.pem
    issuer: "https://localhost:8081/"
    audience: "https://localhost:8081/"
    realm: "Access to Bot"
